export const ingredients = [
  {
    id: 1,
    title: "Acacia's honey",
    highlight: "Acacia's honey",
    image: "/images/imgi_7_acacia.png",
    content:
      "The acacia’s honey is very popular and loved due to its light and delicate taste, we can count on a beekeeper of trust who produces it using a biological method and who provide it to us. His honey is ready in May of each year and has a very light and shiny color. Moreover, its scent is flowered and the taste is delicate, these qualities are transmitted to Principio during the fermentation process.",
  },
  {
    id: 2,
    title: "Carpathian millefiori",
    highlight: "Carpathian",
    image: "/images/imgi_8_carpazi.png",
    content:
      "This honey comes from the green carpathians regions, where there are many types of different flowers. The honey generated by these lands is a millefiori which may vary every year, characterized by a sweet taste and a persistent and flowered scents. We have chosen this honey because it gives a sweet and balanced note.",
  },
  {
    id: 3,
    title: "Manuka’s honey",
    highlight: "Manuka’s honey",
    image: "/images/imgi_9_manuka.png",
    content:
      "Manuka’s honey comes from New Zealand, where have been discovered its unique and potential beneficial properties that make this honey really particular and appreciated. We use a small amount of it in our assembly of honeys in order to transfer its properties and its earthy and herbaceous singular tastes.",
  },
  {
    id: 4,
    title: "Honeydew's honey",
    highlight: "Honeydew's honey",
    image: "/images/imgi_10_melata.png",
    content:
      "The honeydew is a honey that bees create from the sap that some insects produce after swallowing parts of certain trees, it is a very unique honey because it is not obtained from flowers, despite this it is very used and popular. We have chosen to include it in our assembly because of its many polyphenols and its malty and vegetable taste.",
  },
  {
    id: 5,
    title: "Autumn flower's honey",
    highlight: "Autumn flower's honey",
    image: "/images/imgi_11_flowers.png",
    content:
      "The autumn flower’s honey is very rare due to the limited and variable flowering of the plants that the bees use to produce it, this fact leads us to change from time to time the quantities that we use in our assembly. For these reasons it is our favorite, because it is characterized by very fruity smells and tastes and unique properties thanks to the secret types of flowers used for the production.",
  },
  {
    id: 6,
    title: "Chestnut's honey",
    highlight: "Chestnut's honey",
    image: "/images/imgi_12_chestnuts.png",
    content:
      "The chestnut’s honey is produced in hilly and mountain areas; it is usually underappreciated because of its bitter and sharp taste, characteristics which we appreciate because are able to bring bitter shades to our product. These shades are important because they contrast the sweetness of the other honeys included in our assembly.",
  },
];